# Tomcat 베이스 이미지 사용
FROM tomcat:9.0

# 호스트의 볼룸 설정
VOLUME /temp

# WAR 파일을 Tomcat의 webapps 디렉토리에 복사
# COPY IH5demo-2024-08-02-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/

# Tomcat의 기본 포트
EXPOSE 8081

